[package]
name = "zephyr"
version = "0.1.1"
edition = "2021"
description = "Zephyr — privacy-first, ultra-light browser built in Rust"
authors = ["salim77007j"]

[features]
default = ["gui"]
gui = ["tao", "wry", "gtk"]
tao = ["dep:tao"]
wry = ["dep:wry"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
tiny_http = "0.12"
ureq = { version = "2", features = ["tls", "gzip"] }
aes-gcm = "0.10"
rand = "0.8"
dirs = "5"
url = "2"
base64 = "0.22"
crossbeam-channel = "0.5"
raw-window-handle = "0.6"
tao = { version = "0.33", optional = true }
wry = { version = "0.51", optional = true, features = ["devtools"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
gtk = { version = "0.18", optional = true }

[profile.release]
opt-level = 2
lto = "thin"
strip = "symbols"
codegen-units = 1
panic = "abort"

[package.metadata.deb]
maintainer = "salim77007j"
depends = "libwebkit2gtk-4.1-0, libgtk-3-0"
section = "web"
priority = "optional"
extended-description = "Zephyr is a privacy-first, ultra-light web browser with built-in ad, tracker and fingerprint protection."
